### ISSUE TITLE
Protocol message tag had invalid wire type - sometimes happen.

### ISSUE THREAD

**Issue by mack94** [mack94/urban-traffic-monitoring-application#5]
com.google.protobuf.InvalidProtocolBufferException: Protocol message tag had invalid wire type

```
$ routeIdx: 6
secondOfDay: 75590
duration: 311
dayOfWeek: 6
message: "No message"

routeIdx: 6
secondOfDay: 75633
duration: 327
dayOfWeek: 6
message: "No message"

com.google.protobuf.InvalidProtocolBufferException: Protocol message tag had invalid wire type.
	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:111)
	at com.google.protobuf.CodedInputStream.skipField(CodedInputStream.java:201)
	at pl.edu.agh.pp.charts.operations.AnomalyOperationProtos$AnomalyMessage.<init>(AnomalyOperationProtos.java:1661)
	at pl.edu.agh.pp.charts.operations.AnomalyOperationProtos$AnomalyMessage.<init>(AnomalyOperationProtos.java:1624)
	at pl.edu.agh.pp.charts.operations.AnomalyOperationProtos$AnomalyMessage$1.parsePartialFrom(AnomalyOperationProtos.java:2382)
	at pl.edu.agh.pp.charts.operations.AnomalyOperationProtos$AnomalyMessage$1.parsePartialFrom(AnomalyOperationProtos.java:2377)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:139)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:173)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:190)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at pl.edu.agh.pp.charts.operations.AnomalyOperationProtos$AnomalyMessage.parseFrom(AnomalyOperationProtos.java:1928)
	at pl.edu.agh.pp.charts.adapters.ChannelReceiver.receive(ChannelReceiver.java:83)
	at org.jgroups.blocks.cs.NioConnection._receive(NioConnection.java:239)
	at org.jgroups.blocks.cs.NioConnection$Reader._run(NioConnection.java:454)
	at org.jgroups.blocks.cs.NioConnection$Reader.run(NioConnection.java:443)
	at java.lang.Thread.run(Thread.java:745)
routeIdx: 6
secondOfDay: 75818
duration: 297
dayOfWeek: 6
message: "No message"

com.google.protobuf.InvalidProtocolBufferException: Protocol message tag had invalid wire type.
	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:111)
	at com.google.protobuf.CodedInputStream.skipField(CodedInputStream.java:201)
	at pl.edu.agh.pp.charts.operations.AnomalyOperationProtos$AnomalyMessage.<init>(AnomalyOperationProtos.java:1661)
	at pl.edu.agh.pp.charts.operations.AnomalyOperationProtos$AnomalyMessage.<init>(AnomalyOperationProtos.java:1624)
	at pl.edu.agh.pp.charts.operations.AnomalyOperationProtos$AnomalyMessage$1.parsePartialFrom(AnomalyOperationProtos.java:2382)
	at pl.edu.agh.pp.charts.operations.AnomalyOperationProtos$AnomalyMessage$1.parsePartialFrom(AnomalyOperationProtos.java:2377)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:139)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:173)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:190)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at pl.edu.agh.pp.charts.operations.AnomalyOperationProtos$AnomalyMessage.parseFrom(AnomalyOperationProtos.java:1928)
	at pl.edu.agh.pp.charts.adapters.ChannelReceiver.receive(ChannelReceiver.java:83)
	at org.jgroups.blocks.cs.NioConnection._receive(NioConnection.java:239)
	at org.jgroups.blocks.cs.NioConnection$Reader._run(NioConnection.java:454)
	at org.jgroups.blocks.cs.NioConnection$Reader.run(NioConnection.java:443)
	at java.lang.Thread.run(Thread.java:745)
routeIdx: 4
secondOfDay: 75991
duration: 292
dayOfWeek: 6
message: "No message"

routeIdx: 6
secondOfDay: 76188
duration: 218
dayOfWeek: 6
message: "No message"

routeIdx: 6
secondOfDay: 76213
duration: 208
dayOfWeek: 6
message: "No message"


```

**Comment by mack94** [comment]
It happens because not all messages are being sent properly. 
**Need to be resolved as fast as possible.**

**Comment by mack94** [comment]
It is also repaired. All messages are being sent now. 
The TcpClient is used instead of NioClient... but please notice that both are TCP communication.

**Comment by mack94** [comment]
Unfortunately... many messages at the same time still cause this problem.

**Comment by mack94** [comment]
log from the client app. 
The first number in format (%i_%i) is the expected buff length, the second one is the received. 

```
------ Message: 59 _ 59

------ Message: 60 _ 60

ChannelReceiver :: InvalidProtocolBufferException: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
 Buf Array: [8, 4, 16, -81, -14, 3, 32, -101, 15, 40, 4, 48, 2, 58, 16, 69, 114, 114, 111, 114, 32, 114, 97, 116, 101, 58, 32, 49, 53, 32, 37, 64, -11, -111, -92, -65, -2, 42, 74, 19, 50, 48, 49, 54, 45, 49, 48, 45, 50, 49, 32, 49, 55, 58, 52, 51, 58, 49, 49, 48]
 Message: 60 _ 59

------ Message: 60 _ 60

------ Message: 60 _ 60

------ Message: 60 _ 60

ChannelReceiver :: InvalidProtocolBufferException: com.google.protobuf.InvalidProtocolBufferException: Protocol message tag had invalid wire type.
 Buf Array: [8, 18, 16, -76, -14, 3, 32, -61, 9, 40, 4, 48, 2, 58, 16, 69, 114, 114, 111, 114, 32, 114, 97, 116, 101, 58, 32, 49, 56, 32, 37, 64, -16, -68, -92, -65, -2, 42, 74, 19, 50, 48, 49, 54, 45, 49, 48, 45, 50, 49, 32, 49, 55, 58, 52, 51, 58, 49, 55, 54]
 Message: 60 _ 59

ChannelReceiver :: InvalidProtocolBufferException: com.google.protobuf.InvalidProtocolBufferException: Protocol message tag had invalid wire type.
 Buf Array: [8, 20, 16, -75, -14, 3, 32, -75, 6, 40, 4, 48, 1, 58, 16, 69, 114, 114, 111, 114, 32, 114, 97, 116, 101, 58, 32, 51, 53, 32, 37, 64, -116, -61, -92, -65, -2, 42, 74, 19, 50, 48, 49, 54, 45, 49, 48, 45, 50, 49, 32, 49, 55, 58, 52, 51, 58, 49, 55, 54]
 Message: 60 _ 59

------ Message: 60 _ 60

ChannelReceiver :: InvalidProtocolBufferException: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
 Buf Array: [8, 22, 16, -74, -14, 3, 32, -54, 5, 40, 4, 48, 2, 58, 16, 69, 114, 114, 111, 114, 32, 114, 97, 116, 101, 58, 32, 49, 53, 32, 37, 64, -97, -55, -92, -65, -2, 42, 74, 19, 50, 48, 49, 54, 45, 49, 48, 45, 50, 49, 32, 49, 55, 58, 52, 51, 58, 49, 56, 56]
 Message: 60 _ 59

ChannelReceiver :: InvalidProtocolBufferException: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
 Buf Array: [8, 27, 16, -72, -14, 3, 32, -34, 7, 40, 4, 48, 1, 58, 16, 69, 114, 114, 111, 114, 32, 114, 97, 116, 101, 58, 32, 54, 50, 32, 37, 64, -64, -40, -92, -65, -2, 42, 74, 19, 50, 48, 49, 54, 45, 49, 48, 45, 50, 49, 32, 49, 55, 58, 52, 51, 58, 50, 48, 56]
 Message: 60 _ 59

ChannelReceiver :: InvalidProtocolBufferException: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
 Buf Array: [8, 28, 16, -72, -14, 3, 32, -75, 9, 40, 4, 48, 1, 58, 16, 69, 114, 114, 111, 114, 32, 114, 97, 116, 101, 58, 32, 51, 53, 32, 37, 64, -53, -37, -92, -65, -2, 42, 74, 19, 50, 48, 49, 54, 45, 49, 48, 45, 50, 49, 32, 49, 55, 58, 52, 51, 58, 50, 48, 56]
 Message: 60 _ 59

------ Message: 60 _ 60

ChannelReceiver :: InvalidProtocolBufferException: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
 Buf Array: [8, 34, 16, -69, -14, 3, 32, 113, 40, 4, 48, 4, 58, 17, 69, 114, 114, 111, 114, 32, 114, 97, 116, 101, 58, 32, 45, 52, 49, 32, 37, 64, -127, -19, -92, -65, -2, 42, 74, 19, 50, 48, 49, 54, 45, 49, 48, 45, 50, 49, 32, 49, 55, 58, 52, 51, 58, 50, 51, 50]
 Message: 60 _ 59

ChannelReceiver :: InvalidProtocolBufferException: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
 Buf Array: [8, 35, 16, -69, -14, 3, 32, 65, 40, 4, 58, 18, 69, 114, 114, 111, 114, 32, 114, 97, 116, 101, 58, 32, 45, 49, 49, 51, 32, 37, 64, -71, -17, -92, -65, -2, 42, 74, 19, 50, 48, 49, 54, 45, 49, 48, 45, 50, 49, 32, 49, 55, 58, 52, 51, 58, 50, 51, 51, 50]
 Message: 60 _ 58

ChannelReceiver :: InvalidProtocolBufferException: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
 Buf Array: [8, 36, 16, -69, -14, 3, 32, 81, 40, 4, 58, 18, 69, 114, 114, 111, 114, 32, 114, 97, 116, 101, 58, 32, 45, 49, 48, 49, 32, 37, 64, -63, -14, -92, -65, -2, 42, 74, 19, 50, 48, 49, 54, 45, 49, 48, 45, 50, 49, 32, 49, 55, 58, 52, 51, 58, 50, 51, 51, 50]
 Message: 60 _ 58

------ Message: 60 _ 60

ChannelReceiver :: InvalidProtocolBufferException: com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
 Buf Array: [8, 42, 16, -66, -14, 3, 32, -127, 2, 40, 4, 48, 1, 58, 16, 69, 114, 114, 111, 114, 32, 114, 97, 116, 101, 58, 32, 53, 52, 32, 37, 64, -112, -124, -91, -65, -2, 42, 74, 19, 50, 48, 49, 54, 45, 49, 48, 45, 50, 49, 32, 49, 55, 58, 52, 51, 58, 50, 54, 52]
 Message: 60 _ 59

ChannelReceiver :: InvalidProtocolBufferException: com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
 Buf Array: [8, 44, 16, -66, -14, 3, 32, -24, 6, 40, 4, 48, 2, 58, 16, 69, 114, 114, 111, 114, 32, 114, 97, 116, 101, 58, 32, 50, 49, 32, 37, 64, -73, -118, -91, -65, -2, 42, 74, 19, 50, 48, 49, 54, 45, 49, 48, 45, 50, 49, 32, 49, 55, 58, 52, 51, 58, 50, 54, 52]
 Message: 60 _ 59

ChannelReceiver :: InvalidProtocolBufferException: com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
 Buf Array: [8, 45, 16, -65, -14, 3, 32, -54, 9, 40, 4, 48, 1, 58, 16, 69, 114, 114, 111, 114, 32, 114, 97, 116, 101, 58, 32, 51, 56, 32, 37, 64, -125, -114, -91, -65, -2, 42, 74, 19, 50, 48, 49, 54, 45, 49, 48, 45, 50, 49, 32, 49, 55, 58, 52, 51, 58, 50, 55, 52]
 Message: 60 _ 59

ChannelReceiver :: InvalidProtocolBufferException: com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
 Buf Array: [8, 46, 16, -65, -14, 3, 32, -126, 2, 40, 4, 48, 1, 58, 16, 69, 114, 114, 111, 114, 32, 114, 97, 116, 101, 58, 32, 51, 53, 32, 37, 64, -22, -113, -91, -65, -2, 42, 74, 19, 50, 48, 49, 54, 45, 49, 48, 45, 50, 49, 32, 49, 55, 58, 52, 51, 58, 50, 55, 52]
 Message: 60 _ 59

ChannelReceiver :: InvalidProtocolBufferException: com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
 Buf Array: [8, 47, 16, -65, -14, 3, 32, -119, 7, 40, 4, 48, 2, 58, 16, 69, 114, 114, 111, 114, 32, 114, 97, 116, 101, 58, 32, 49, 57, 32, 37, 64, -20, -110, -91, -65, -2, 42, 74, 19, 50, 48, 49, 54, 45, 49, 48, 45, 50, 49, 32, 49, 55, 58, 52, 51, 58, 50, 55, 52]
 Message: 60 _ 59

------ Message: 60 _ 60

------ Message: 60 _ 60

------ Message: 60 _ 60

------ Message: 60 _ 60

------ Message: 60 _ 60

------ Message: 60 _ 60

```

**Comment by mack94** [comment]
## Some tests have been done.

Results from them: **0 / 549** [_errors/messages_]
**Success**

If somebody find this error again, please report this to me, or reopen this issue.
